import os

class Config:
    SQLALCHEMY_DATABASE_USER = os.getenv('MYSQL_DB_USER', 'web_app_service_acc')
    SQLALCHEMY_DATABASE_PASSWORD = os.getenv('MYSQL_DB_PWD', 'cloudsvc#8197')
    SQLALCHEMY_DATABASE_HOST = os.getenv('MYSQL_HOST', 'localhost')
    SQLALCHEMY_DATABASE_NAME = os.getenv('MYSQL_DB_NAME', 'cloud_web_app')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    
    SQLALCHEMY_DATABASE_URI = f"mysql://{SQLALCHEMY_DATABASE_USER}:{SQLALCHEMY_DATABASE_PASSWORD}@{SQLALCHEMY_DATABASE_HOST}/{SQLALCHEMY_DATABASE_NAME}"
    